title: Tshimologo Molefyane
logo: "assets/img/corp_ig.jpg?raw=true"
description:
<avhref="https://www.linkedin.com/in/tshimologo-molefyane247/">View my LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: G-71F72Y0L8G
